import React, { useState } from 'react'
import {
  FileText,
  Copy,
  Check,
  Download,
  X,
  ExternalLink,
  Sparkles,
  ShieldCheck,
  AlertTriangle,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useNavigate } from 'react-router-dom'

interface CopilotStoreBriefModalProps {
  isOpen: boolean
  onClose: () => void
}

export const CopilotStoreBriefModal: React.FC<CopilotStoreBriefModalProps> = ({
  isOpen,
  onClose,
}) => {
  const navigate = useNavigate()
  const [isCopied, setIsCopied] = useState(false)

  if (!isOpen) return null

  const briefText = `MORNING OPERATIONS BRIEF — STORE 01 (CHENNAI CENTRAL)
Date: ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
Generated by: Retail Edge OS Store AI Copilot (Jetson Orin NX)

EXECUTIVE OVERVIEW:
• Store Footfall is currently 14% above typical levels for this period (1,284 total visits).
• Overall Shelf Health is 86%, with Beverage Gondola B4 and Dairy Cooler Wall D2 requiring immediate replenishment.
• Checkout Counter C1 has a 92% probability of critical queue congestion within 5 minutes.

OPERATIONAL PRIORITIES:
1. Replenish Beverage Shelf B4 (24 units from Backroom Bay 3B).
2. Open Standby Counter C3 to relieve Counter C1 congestion.
3. Reallocate Associate S02 (Marcus Vance) to checkout billing support.

RISK MATRIX:
• 2 Inventory depletion risks (B4, D2)
• 1 Queue SLA breach risk (Counter C1)
• 0 System hardware issues (6/6 Cameras online, TensorRT nominal)`

  const handleCopy = () => {
    navigator.clipboard.writeText(briefText)
    setIsCopied(true)
    setTimeout(() => setIsCopied(false), 2000)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 select-none font-mono">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/70 backdrop-blur-xs transition-opacity animate-in fade-in-0"
        onClick={onClose}
      />

      {/* Modal Dialog */}
      <div className="relative w-full max-w-lg rounded-xl border border-[#1E293B] bg-[#0B0F17] p-5 shadow-2xl z-10 space-y-4 animate-in zoom-in-95 duration-150 text-xs">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-[#1E293B]">
          <div className="flex items-center gap-2">
            <div className="p-1 rounded bg-cyan-950 border border-cyan-500/40 text-cyan-400">
              <FileText className="h-4 w-4" />
            </div>
            <div>
              <h3 className="text-xs font-bold text-white uppercase tracking-wider font-mono">
                Store Operations Brief
              </h3>
              <span className="text-[10px] text-cyan-400">
                Automated Operational Intelligence Digest
              </span>
            </div>
          </div>

          <Button variant="ghost" size="icon-xs" onClick={onClose} className="text-slate-400 hover:text-white">
            <X className="h-4 w-4" />
          </Button>
        </div>

        {/* Content Box */}
        <div className="p-3.5 rounded-lg bg-[#090D14] border border-[#1E293B] space-y-3 font-mono text-[11px] text-slate-200">
          <div className="text-cyan-300 font-bold border-b border-slate-800 pb-1.5 flex justify-between">
            <span>MORNING OPERATIONS BRIEF</span>
            <span className="text-[9px] text-slate-400">Store 01 • Chennai Central</span>
          </div>

          <p className="text-slate-300 font-sans leading-relaxed">
            Traffic is currently <strong className="text-cyan-300">14% above</strong> the typical level for this time period. Shelf health is <strong className="text-emerald-400">86%</strong>, with Beverage B4 and Dairy D2 requiring attention. Checkout C1 has a <strong className="text-rose-400">92% probability</strong> of congestion within five minutes.
          </p>

          {/* Priorities */}
          <div className="space-y-1 bg-[#0F172A] p-2.5 rounded border border-[#1E293B]">
            <span className="text-[10px] font-bold text-white uppercase block">
              Immediate Priorities:
            </span>
            <div className="space-y-0.5 text-slate-300 font-sans text-xs">
              <div>1. Replenish Beverage B4 (24 units from Bay 3B)</div>
              <div>2. Open Standby Counter C3</div>
              <div>3. Assign S02 (Marcus Vance) to billing support</div>
            </div>
          </div>

          {/* Risks Summary */}
          <div className="grid grid-cols-3 gap-2 text-center text-[10px]">
            <div className="bg-[#0F172A] p-1.5 rounded border border-amber-500/40">
              <span className="text-slate-500 block">Inventory</span>
              <strong className="text-amber-300">2 Risks</strong>
            </div>
            <div className="bg-[#0F172A] p-1.5 rounded border border-rose-500/40">
              <span className="text-slate-500 block">Queue</span>
              <strong className="text-rose-400">1 Risk</strong>
            </div>
            <div className="bg-[#0F172A] p-1.5 rounded border border-emerald-500/40">
              <span className="text-slate-500 block">Edge Hardware</span>
              <strong className="text-emerald-400">0 Critical</strong>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between pt-2 border-t border-[#1E293B]">
          <Button
            variant="outline"
            size="xs"
            onClick={() => {
              onClose()
              navigate('/reports-insights')
            }}
            className="text-[11px] h-7 px-2.5 text-slate-300 border-[#1E293B] gap-1"
          >
            <ExternalLink className="h-3.5 w-3.5 text-cyan-400" />
            <span>Open Reports & Insights</span>
          </Button>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="xs"
              onClick={handleCopy}
              className="text-[11px] h-7 px-2.5 text-cyan-300 border-[#1E293B] gap-1 font-mono"
            >
              {isCopied ? <Check className="h-3 w-3 text-emerald-400" /> : <Copy className="h-3 w-3" />}
              <span>{isCopied ? 'Copied' : 'Copy Summary'}</span>
            </Button>

            <Button
              variant="action"
              size="xs"
              onClick={() => {
                alert('Store brief saved to Reports history.')
                onClose()
              }}
              className="text-[11px] h-7 px-2.5 font-mono"
            >
              <span>Save Brief</span>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
