import React, { useState } from 'react'
import {
  FileText,
  Copy,
  Check,
  Download,
  X,
  ExternalLink,
  Sparkles,
  ShieldCheck,
  AlertTriangle,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useNavigate } from 'react-router-dom'

interface CopilotStoreBriefModalProps {
  isOpen: boolean
  onClose: () => void
}

export const CopilotStoreBriefModal: React.FC<CopilotStoreBriefModalProps> = ({
  isOpen,
  onClose,
}) => {
  const navigate = useNavigate()
  const [isCopied, setIsCopied] = useState(false)

  if (!isOpen) return null

  const briefText = `MORNING OPERATIONS BRIEF — STORE 01 (CHENNAI CENTRAL)
Date: ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
Generated by: Retail Edge OS Store AI Copilot (Jetson Orin NX)

EXECUTIVE OVERVIEW:
• Store Footfall is currently 14% above typical levels for this period (1,284 total visits).
• Overall Shelf Health is 86%, with Beverage Gondola B4 and Dairy Cooler Wall D2 requiring immediate replenishment.
• Checkout Counter C1 has a 92% probability of critical queue congestion within 5 minutes.

OPERATIONAL PRIORITIES:
1. Replenish Beverage Shelf B4 (24 units from Backroom Bay 3B).
2. Open Standby Counter C3 to relieve Counter C1 congestion.
3. Reallocate Associate S02 (Marcus Vance) to checkout billing support.

RISK MATRIX:
• 2 Inventory depletion risks (B4, D2)
• 1 Queue SLA breach risk (Counter C1)
• 0 System hardware issues (6/6 Cameras online, TensorRT nominal)`

  const handleCopy = () => {
    navigator.clipboard.writeText(briefText)
    setIsCopied(true)
    setTimeout(() => setIsCopied(false), 2000)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 select-none font-sans">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs transition-opacity animate-in fade-in-0"
        onClick={onClose}
      />

      {/* Modal Dialog */}
      <div className="relative w-full max-w-lg rounded-xl border border-slate-200 bg-white p-5 shadow-2xl z-10 space-y-4 animate-in zoom-in-95 duration-150 text-xs">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div className="flex items-center gap-2">
            <div className="p-1 rounded-md bg-sky-50 border border-sky-200 text-sky-600">
              <FileText className="h-4 w-4" />
            </div>
            <div>
              <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
                Store Operations Brief
              </h3>
              <span className="text-[10px] text-sky-700 font-semibold">
                Automated Operational Intelligence Digest
              </span>
            </div>
          </div>

          <Button variant="ghost" size="icon-xs" onClick={onClose} className="text-slate-400 hover:text-slate-900">
            <X className="h-4 w-4" />
          </Button>
        </div>

        {/* Content Box */}
        <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-3 text-[11px] text-slate-700 shadow-2xs">
          <div className="text-sky-700 font-bold border-b border-slate-200 pb-1.5 flex justify-between font-sans">
            <span>MORNING OPERATIONS BRIEF</span>
            <span className="text-[9px] text-slate-400 font-mono">Store 01 • Chennai Central</span>
          </div>

          <p className="text-slate-700 leading-relaxed">
            Traffic is currently <strong className="text-sky-700">14% above</strong> the typical level for this time period. Shelf health is <strong className="text-emerald-700">86%</strong>, with Beverage B4 and Dairy D2 requiring attention. Checkout C1 has a <strong className="text-rose-700">92% probability</strong> of congestion within five minutes.
          </p>

          {/* Priorities */}
          <div className="space-y-1 bg-white p-3 rounded-lg border border-slate-200 shadow-2xs">
            <span className="text-[10px] font-bold text-slate-900 uppercase block">
              Immediate Priorities:
            </span>
            <div className="space-y-0.5 text-slate-700 text-xs">
              <div>1. Replenish Beverage B4 (24 units from Bay 3B)</div>
              <div>2. Open Standby Counter C3</div>
              <div>3. Assign S02 (Marcus Vance) to billing support</div>
            </div>
          </div>

          {/* Risks Summary */}
          <div className="grid grid-cols-3 gap-2 text-center text-[10px]">
            <div className="bg-white p-2 rounded-lg border border-amber-200 shadow-2xs">
              <span className="text-slate-500 block">Inventory</span>
              <strong className="text-amber-800 font-bold">2 Risks</strong>
            </div>
            <div className="bg-white p-2 rounded-lg border border-rose-200 shadow-2xs">
              <span className="text-slate-500 block">Queue</span>
              <strong className="text-rose-700 font-bold">1 Risk</strong>
            </div>
            <div className="bg-white p-2 rounded-lg border border-emerald-200 shadow-2xs">
              <span className="text-slate-500 block">Edge Hardware</span>
              <strong className="text-emerald-700 font-bold">0 Critical</strong>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between pt-2 border-t border-slate-100">
          <Button
            variant="outline"
            size="xs"
            onClick={() => {
              onClose()
              navigate('/reports-insights')
            }}
            className="text-[11px] h-7 px-2.5 text-slate-700 border-slate-200 bg-white hover:bg-slate-50 gap-1 shadow-2xs font-semibold"
          >
            <ExternalLink className="h-3.5 w-3.5 text-sky-600" />
            <span>Open Reports & Insights</span>
          </Button>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="xs"
              onClick={handleCopy}
              className="text-[11px] h-7 px-2.5 text-slate-700 border-slate-200 bg-white hover:bg-slate-50 gap-1 shadow-2xs font-semibold"
            >
              {isCopied ? <Check className="h-3 w-3 text-emerald-600" /> : <Copy className="h-3 w-3" />}
              <span>{isCopied ? 'Copied' : 'Copy Summary'}</span>
            </Button>

            <Button
              variant="action"
              size="xs"
              onClick={() => {
                alert('Store brief saved to Reports history.')
                onClose()
              }}
              className="text-[11px] h-7 px-2.5 bg-sky-600 hover:bg-sky-700 text-white font-semibold"
            >
              <span>Save Brief</span>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
