import React, { useMemo, useState } from 'react'
import {
  FileText,
  Copy,
  Check,
  Download,
  X,
  ExternalLink,
  Sparkles,
  ShieldCheck,
  AlertTriangle,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useNavigate } from 'react-router-dom'
import { useAppStore } from '@/store/useAppStore'
import { formatNumber } from '@/lib/utils'

interface CopilotStoreBriefModalProps {
  isOpen: boolean
  onClose: () => void
}

export const CopilotStoreBriefModal: React.FC<CopilotStoreBriefModalProps> = ({
  isOpen,
  onClose,
}) => {
  const navigate = useNavigate()
  const [isCopied, setIsCopied] = useState(false)

  const currentOccupancy = useAppStore((s) => s.currentOccupancy)
  const todaysTotalFootfall = useAppStore((s) => s.todaysTotalFootfall)
  const storeInfo = useAppStore((s) => s.storeInfo)
  const shelfItems = useAppStore((s) => s.shelfItems)
  const queues = useAppStore((s) => s.queues)
  const incidents = useAppStore((s) => s.incidents)
  const cameraSummary = useAppStore((s) => s.cameraSummary)
  const staffMembers = useAppStore((s) => s.staffMembers)

  const avgAvailability = shelfItems.length > 0
    ? Math.round(
        (shelfItems.reduce((acc, s) => acc + (s.capacityCount > 0 ? s.currentCount / s.capacityCount : 0), 0) /
          shelfItems.length) *
          100
      )
    : 100

  const criticalShelves = shelfItems
    .filter((s) => s.status === 'CRITICAL' || s.status === 'OUT_OF_STOCK')
    .slice(0, 3)

  const congestedLanes = queues.filter((q) => q.status === 'CONGESTED')

  const openIncidents = incidents.filter((i) => i.status !== 'RESOLVED' && i.status !== 'DISMISSED')
  const criticalIncidents = openIncidents.filter((i) => i.severity === 'critical')
  const highIncidents = openIncidents.filter((i) => i.severity === 'high')

  const availableStaff = staffMembers.filter((s) => s.status === 'ON_DUTY_AVAILABLE')

  const generatedDate = useMemo(
    () => new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    []
  )

  if (!isOpen) return null

  const priorities: string[] = []
  criticalShelves.forEach((s) => priorities.push(`Replenish ${s.productName} (${s.shelfName}, ${s.zoneName})`))
  congestedLanes.forEach((q) => priorities.push(`Open additional support for congested Lane ${q.laneNumber}`))
  if (priorities.length === 0) priorities.push('No urgent operational priorities detected')

  const briefText = `STORE OPERATIONS BRIEF — ${storeInfo?.name || 'STORE'}
Date: ${generatedDate}
Generated by: Retail Edge OS Store AI Copilot (from live store data)

EXECUTIVE OVERVIEW:
• Current occupancy is ${currentOccupancy}${storeInfo?.maxCapacity ? ` (${Math.round((currentOccupancy / storeInfo.maxCapacity) * 100)}% of capacity)` : ''}, with ${formatNumber(todaysTotalFootfall)} total visits today.
• Overall shelf availability is ${avgAvailability}%, with ${criticalShelves.length} shelf item(s) critically low or out of stock.
• ${congestedLanes.length} checkout lane(s) currently congested.

OPERATIONAL PRIORITIES:
${priorities.map((p, i) => `${i + 1}. ${p}`).join('\n')}

RISK MATRIX:
• ${criticalShelves.length} inventory depletion risk(s)
• ${congestedLanes.length} queue congestion risk(s)
• ${cameraSummary.offlineCameras} camera(s) offline (${cameraSummary.onlineCameras}/${cameraSummary.totalCameras} online)
• ${criticalIncidents.length} critical incident(s), ${highIncidents.length} high severity incident(s) open
• ${availableStaff.length} staff member(s) currently available`

  const handleCopy = () => {
    navigator.clipboard.writeText(briefText)
    setIsCopied(true)
    setTimeout(() => setIsCopied(false), 2000)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 select-none font-sans">
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs transition-opacity animate-in fade-in-0"
        onClick={onClose}
      />

      {/* Modal Dialog */}
      <div className="relative w-full max-w-lg rounded-xl border border-slate-200 bg-white p-5 shadow-2xl z-10 space-y-4 animate-in zoom-in-95 duration-150 text-xs">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div className="flex items-center gap-2">
            <div className="p-1 rounded-md bg-sky-50 border border-sky-200 text-sky-600">
              <FileText className="h-4 w-4" />
            </div>
            <div>
              <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
                Store Operations Brief
              </h3>
              <span className="text-[10px] text-sky-700 font-semibold">
                Automated Operational Intelligence Digest
              </span>
            </div>
          </div>

          <Button variant="ghost" size="icon-xs" onClick={onClose} className="text-slate-400 hover:text-slate-900">
            <X className="h-4 w-4" />
          </Button>
        </div>

        {/* Content Box */}
        <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-3 text-[11px] text-slate-700 shadow-2xs">
          <div className="text-sky-700 font-bold border-b border-slate-200 pb-1.5 flex justify-between font-sans">
            <span>STORE OPERATIONS BRIEF</span>
            <span className="text-[9px] text-slate-400 font-mono">{storeInfo?.name || 'Store'}</span>
          </div>

          <p className="text-slate-700 leading-relaxed">
            Current occupancy is <strong className="text-sky-700">{currentOccupancy}</strong>
            {storeInfo?.maxCapacity ? ` (${Math.round((currentOccupancy / storeInfo.maxCapacity) * 100)}% of capacity)` : ''}, with <strong className="text-slate-900">{formatNumber(todaysTotalFootfall)}</strong> total visits today. Shelf availability is <strong className="text-emerald-700">{avgAvailability}%</strong>, with <strong className={criticalShelves.length > 0 ? 'text-rose-700' : 'text-emerald-700'}>{criticalShelves.length}</strong> item(s) critically low. <strong className={congestedLanes.length > 0 ? 'text-rose-700' : 'text-emerald-700'}>{congestedLanes.length}</strong> checkout lane(s) are congested.
          </p>

          {/* Priorities */}
          <div className="space-y-1 bg-white p-3 rounded-lg border border-slate-200 shadow-2xs">
            <span className="text-[10px] font-bold text-slate-900 uppercase block">
              Immediate Priorities:
            </span>
            <div className="space-y-0.5 text-slate-700 text-xs">
              {priorities.map((p, i) => (
                <div key={i}>{i + 1}. {p}</div>
              ))}
            </div>
          </div>

          {/* Risks Summary */}
          <div className="grid grid-cols-3 gap-2 text-center text-[10px]">
            <div className="bg-white p-2 rounded-lg border border-amber-200 shadow-2xs">
              <span className="text-slate-500 block">Inventory</span>
              <strong className="text-amber-800 font-bold">{criticalShelves.length} Risk{criticalShelves.length === 1 ? '' : 's'}</strong>
            </div>
            <div className="bg-white p-2 rounded-lg border border-rose-200 shadow-2xs">
              <span className="text-slate-500 block">Queue</span>
              <strong className="text-rose-700 font-bold">{congestedLanes.length} Risk{congestedLanes.length === 1 ? '' : 's'}</strong>
            </div>
            <div className="bg-white p-2 rounded-lg border border-emerald-200 shadow-2xs">
              <span className="text-slate-500 block">Edge Hardware</span>
              <strong className="text-emerald-700 font-bold">{cameraSummary.offlineCameras} Critical</strong>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between pt-2 border-t border-slate-100">
          <Button
            variant="outline"
            size="xs"
            onClick={() => {
              onClose()
              navigate('/reports-insights')
            }}
            className="text-[11px] h-7 px-2.5 text-slate-700 border-slate-200 bg-white hover:bg-slate-50 gap-1 shadow-2xs font-semibold"
          >
            <ExternalLink className="h-3.5 w-3.5 text-sky-600" />
            <span>Open Reports & Insights</span>
          </Button>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="xs"
              onClick={handleCopy}
              className="text-[11px] h-7 px-2.5 text-slate-700 border-slate-200 bg-white hover:bg-slate-50 gap-1 shadow-2xs font-semibold"
            >
              {isCopied ? <Check className="h-3 w-3 text-emerald-600" /> : <Copy className="h-3 w-3" />}
              <span>{isCopied ? 'Copied' : 'Copy Summary'}</span>
            </Button>

            <Button
              variant="action"
              size="xs"
              onClick={() => {
                alert('Store brief saved to Reports history.')
                onClose()
              }}
              className="text-[11px] h-7 px-2.5 bg-sky-600 hover:bg-sky-700 text-white font-semibold"
            >
              <span>Save Brief</span>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
